---
- hosts: web
  remote_user: ubuntu
  become: yes

  tasks:
    - name: apt update
      apt:
        update_cache: yes
    
    - name: install apache
      apt:
        name: apache2
        state: present
    
    - name: "Edit webpage"
      copy:
        content: "<h1> My EC2 Instance! </h1>"
        dest: "/var/www/html/index.html"

      
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted


        